type ProvinceResponse {
    uuid: ID!
    value: String!
    label: String!
}

type ProvincePaginate {
    content: [ProvinceResponse]!
    empty: Boolean
    first: Boolean
    last: Boolean
    number: Int
    numberOfElements: Int
    size: Int
    totalElements: Int
    totalPages: Int
}

input ProvinceRequest {
    value: String!
    label: String!
}

input ProvinceFilterQueryParamInput {
    field: String = "ALL"
    search: String
    pageSize: Int = 10
    pageNumber: Int = 0
}


extend type Query {
    adminPaginateProvince(paginateRequest: PaginateRequest): ProvincePaginate!
    adminPaginateProvinceFilter(filter: ProvinceFilterQueryParamInput): ProvincePaginate!
    adminFindByUuidProvince(uuid: ID!): ProvinceResponse
    adminFindByValueProvince(value: String!): ProvinceResponse
}

extend type Mutation {
    adminSaveProvince(provinceRequest: ProvinceRequest!): ProvinceResponse
    adminUpdateProvince(uuid: ID!, provinceRequest: ProvinceRequest!): ProvinceResponse
    adminDeleteByUuidProvince(uuid: ID!): Boolean
}
